### PR TITLE
Add support for iframe tag

### PR DESCRIPTION
**Pull request by zaceno**

### CODE REVIEW

**Comment by zaceno** [comment]
Thanks for the ✅ @Swizz 

Should I go ahead and merge? Not sure about the etiquette in this repo 😄

**Comment by Swizz** [comment]
It belongs to the community. I can move forward but not at the moment.

Or maybe only merge and publish later.

**Comment by JorgeBucaran** [comment]
Squash is usually best IMO.

**Comment by lukejacksonn** [comment]
🎉

**Pull request merged**
